### ISSUE TITLE
Possible to add arg type conversion ?

### ISSUE THREAD

**Issue by rockygsm** [gsmk/hexagon#6]
Hello
Its nice to have ida module but its possible to improve this by add some arguments and type ref sync ?
i have log debug binary from OEM if any one want to check and improve module..

R0 i noticed most case use for result on return functions. also we have room to improve p0,new and cmp.eq  stuff.. may be can make more user friendly for us ?

example.

> { call strlen
>   r0 = r18 }

Can be 

> r0 = strlen (r18)

**Comment by nlitsme** [comment]
What you are asking for is a decompiler, that is definitely beyond the scope of a simple disassembler.
My goal is to stay as close as possible to the actual instructions.

About a debug binary: yes, can you please share it with me?

Things i would like to do: add support for stack variables.

**Comment by rockygsm** [comment]
Hello 
i can drop you at email itsme xs4all nl if its ok ?

**Comment by nlitsme** [comment]
> On 1 May 2018, at 18:54, rockymaster <notifications@github.com> wrote:
> 
> Hello
> i can drop you at email itsme xs4all nl if its ok ?
> 

Sure.

willem
