### ISSUE TITLE
New Hexagon processor module

### ISSUE THREAD

**Issue by n-o-o-n** [gsmk/hexagon#7]
You might be interested in [this repository](https://github.com/n-o-o-n/idp_hexagon).

**Comment by XVilka** [comment]
There are others as well, e.g. the one for [radare2](https://github.com/radareorg/radare2)/[Cutter](https://github.com/radareorg/cutter):
- https://github.com/radareorg/r2hexagon
- https://github.com/radareorg/radare2/tree/master/libr/asm/arch/hexagon
- https://github.com/radareorg/radare2/blob/master/libr/asm/p/asm_hexagon.c
- https://github.com/radareorg/radare2/tree/master/libr/anal/arch/hexagon
- https://github.com/radareorg/radare2/blob/master/libr/anal/p/anal_hexagon.c
- https://github.com/radareorg/radare2/blob/master/test/db/asm/hexagon

**Comment by n-o-o-n** [comment]
True, but it doesn't support post-v62 instructions as well as HVX.

**Comment by XVilka** [comment]
I will update it

**Comment by nlitsme** [comment]
thanks for the note, i will add those links to the readme.
